EYAA_site/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("inscription/", views.inscription, name="inscription"),
    path("connexion/", views.connexion, name="connexion"),
    path("contacts/", views.contacts, name="contacts"),
    path("database/", views.database_view, name="genome_database"),
    path("visualisation/<str:obj_type>/<str:obj_id>/", views.visualisation, name="visualisation"),
    path("deconnexion/", views.deconnexion, name="deconnexion"),
    path("profil/", views.profile, name="profile"),
    path('profil/informations/', views.profile_informations, name='profile_informations'),
    path("profil/change_PSWD/", views.profile_change_PSWD, name="profile_change_PSWD"),
    path('profil/annotations/', views.profile_annotations, name='profile_annotations'),
    path("profil/annotations/annotation_detail/<str:sequence_id>/", views.annoter, name="annoter"),
    path("outil_validation/", views.annotations_listing, name="annotations_listing"),
    path("outil_validation/annotation_detail/<str:annotation_id>/", views.validate_annotation, name="validate_annotation"),
    path("attribution_sequence/", views.sequences_non_assigned, name="sequences_non_assigned"),
    path("attribution_sequence/sequence_detail/<str:sequence_id>/", views.attribution_sequence, name="attribution_manuelle"),
    path('extraction/', views.extraction_view, name='extraction'),
    path('extraction_file/', views.extraction_file, name='extraction_file'),
    path('attribution_sequence/attribution_auto', views.attribution_auto, name='attribution_auto'),
    path('access_denied/', views.access_denied, name='access_denied'),
]

core/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib import admin
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin
from django import forms
from django.contrib.auth import get_user_model

# Partie Utilisateur

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


class Utilisateur(models.Model):
    email = models.EmailField(unique=True)
    mot_de_passe = models.CharField(max_length=10)

ROLE_CHOICES = [
    ("lecteur", "Lecteur"),
    ("annotateur", "Annotateur"),
    ("validateur", "Validateur"),
    ("visiteur", "Visiteur"),
]

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True, primary_key=True)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default="visiteur")
    requested_role = models.CharField(max_length=20, choices=ROLE_CHOICES, blank=True, null=True)  # 

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.email} ({self.role})"



class Genome(models.Model):
    genome_id = models.CharField(max_length=20, primary_key=True)

    # Only ACGT or ACGU
    # peut être mettre quelque chose pour vérifier la condition plus tard
    genome_sequence = models.TextField(validators=[RegexValidator(
         regex=r"^[ACGTURYKMSWBDHVN]*$",
         message="La séquence doit être composée uniquement des caractères ACGTURYKMSWBDHVN (norme IUPAC).")])

    TYPE_CHOICES = [("DNA", "ADN"), ("RNA", "ARN")]
    genome_type = models.CharField(max_length=3, choices=TYPE_CHOICES)

    organism = models.CharField(max_length=20)

    is_annotated = models.BooleanField(default=False)

    def __str__(self):
        return str(self.genome_id)


class Sequence(models.Model):
    sequence_id = models.CharField(max_length=20, primary_key=True)
    dna_sequence = models.TextField()
    aa_sequence = models.TextField()
    sequence_start = models.IntegerField()
    sequence_stop = models.IntegerField()
    sequence_length = models.IntegerField()
    
    # On peut ajouter une def() pour calculer automatiquement
    gene_name = models.CharField(max_length=20, blank=True, null=True)
    peptide_product = models.CharField(max_length=20, blank=True, null=True)

    STATUS_CHOICES = [("Nothing", "Non-annotée"),
                      ("Assigned", "Attribuée"),
                      ("Awaiting validation", "En attente de validation"),
                      ("Validated", "Validée")]
    

    BRIN_CHOICES = [(1, "Direct"),
                    (-1, "Indirect"),
                    (0, "Unknown")]
    
    SUPPORT_CHOICES = [("plasmid","Plasmide"),
                       ("chromosome","Chromosome")]
    
    sequence_brin = models.IntegerField( choices=BRIN_CHOICES, default=0)
    sequence_status = models.CharField(max_length=50, choices=STATUS_CHOICES)
    
    information_support = models.CharField(max_length=50, choices=SUPPORT_CHOICES)

    # Relation One-to-Many avec genome
    genome = models.ForeignKey(Genome, on_delete=models.CASCADE,
                               related_name="sequences")

    def __str__(self):
        return str(self.sequence_id)
    
    def length(self):
        return str(self.sequence_id)


class Annotation(models.Model):
    annotation_id = models.CharField(max_length=20, primary_key=True)
    annotation_text = models.TextField()  # Définir un max ?
    annotation_author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="annotations",
                                          blank=True, null=True)
    # On pourrait possiblement ajouter
    # un attribut "date de création" ou de "validation"
    is_validated = models.BooleanField(default=False)
    rejected_comment = models.TextField(blank=True, null=True)
    validation_date = models.DateTimeField(blank=True, null=True)

    # Relation One-to-zero-or-one avec sequence
    sequence = models.OneToOneField(Sequence, on_delete=models.CASCADE,
                                    related_name="annotation")

    def __str__(self):
        return str(self.annotation_id)


class Domaine(models.Model):
    domain_id = models.CharField(max_length=20, primary_key=True)
    domain_name = models.CharField(max_length=20)

    domain_start = models.IntegerField()
    domain_stop = models.IntegerField()
    domain_length = models.IntegerField()
    domain_function = models.CharField(max_length=50)

    # Relation One-to-Many avec sequence
    sequence = models.ForeignKey(Sequence, on_delete=models.CASCADE,
                                 related_name="domaines")
    # sequence.domaines.all() --> récupère tous les domaines
    # liés à la séquence X

    def __str__(self):
        return str(self.domain_id)


# Historique connexion
User = get_user_model()

class ConnectionHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    login_time = models.DateTimeField(default=timezone.now)
    logout_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.email} - {self.login_time}"

core/forms.py
<!-- import_form.html -->
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Importer des génomes</title>
</head>
<body>
    <h1>Importer un fichier FASTA</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Importer</button>
    </form>
</body>
</html>

core/templates/core/attribution_sequence.html
{% extends "core/base.html" %}
{% load static %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Accueil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'sequences_non_assigned' %}">Outil d'attribution</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ sequence.sequence_id }}</li>
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'core/style_attribution.css' %}">

    <div class="attribution-container">
        <h1>Attribution de la séquence</h1>

        <div class="sequence-details">
            <h2>Séquence ID : {{ sequence.sequence_id }}</h2>
            <p><strong>Genome Organism :</strong> {{ sequence.genome.organism }}</p>
            <p><strong>START :</strong>{{ sequence.sequence_start }}&nbsp;
                <strong>STOP :</strong>{{ sequence.sequence_stop }}&nbsp;
                <strong>Longueur :</strong>{{ sequence.sequence_length }}</p>
            <p><strong>Position sur le génome (chromosome) :</strong>{{ sequence.num_chromosome }}</p>
            
            <h3>ADN :</h3>
            <pre style="word-wrap: break-word; white-space: normal; background: #f4f4f4; padding: 10px; border-radius: 5px;height: 150px; overflow-y: auto;">
                {{ sequence.dna_sequence }}
            </pre>
            <h3>Protéine :</h3>
            <pre style="word-wrap: break-word; white-space: normal; background: #f4f4f4; padding: 10px; border-radius: 5px;height: 150px;overflow-y: auto;">
                {{ sequence.aa_sequence }}
            </pre>

        </div>

        <div class="attribution-actions">
            <h3>Choisir un annotateur :</h3>

            <form method="POST">
                {% csrf_token %}

                <label for="annotateur">Sélectionner un annotateur :</label>
                <select id="annotateur" name="annotateur" required>
                    {% if annotateurs %}
                    <option value="" disabled selected>-- Choisir un annotateur --</option>
                    {% for annotateur in annotateurs %}
                        <option value="{{ annotateur.email }}">{{ annotateur.email }} ({{ annotateur.role }}) </option>
                    {% endfor %}
                {% else %}
                    <option value="" disabled selected>Aucun annotateur disponible actuellement</option>
                {% endif %}
                </select>

                <button type="submit">Attribuer</button>

            </form>
        </div>
    </div>
{% endblock %}

core/templates/core/connexion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'core/style_inscription.css' %}">
    <title>Connexion</title>
</head>
<body>
    <div class="container">
        <div class="form">
            <h1>Connexion</h1>
            <form method="post" action="{% url 'connexion' %}">
                {% csrf_token %}
                <label for="email">Adresse email</label>
                <input type="text" name="email" required>

                
                <label for="password">Mot de passe</label>
                <input type="password" name="password" required>
                
                <button type="submit">Se connecter</button>
            </form>
            <p class="link">Pas encore inscrit ? <a href="{% url 'inscription' %}">S'inscrire</a></p>
        </div>
    </div>
</html>

core/templates/core/contacts.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
Contacts - EYAA
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Accueil</a></li>
    <li class="breadcrumb-item active" aria-current="page">Contacts</li>
{% endblock %}

{% block content %}
<div class="contacts">
    <ul style="color: rgb(255, 255, 255);">
        <li><a>Emma Le Roy Pardonche</a></li>
        <li><a>Youna Maillié</a></li>
        <li><a>Anne Beigeaud</a></li>
        <li><a>Antoine Loth</a></li>
    </ul>
</div>

{% endblock %}

core/templates/core/non_connecte.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
Accueil - EYAA
{% endblock %}

{% block content %}


<div class = "titre_non_connecté">Merci de vous connecter</div>
{% endblock %}

core/templates/core/profile_annotations.html
{% extends "core/base_profile.html" %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Accueil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'profile' %}">Profil</a></li>
    <li class="breadcrumb-item active" aria-current="page">Mes Annotations</li>
{% endblock %}

{% block profile_content %}
<div id="annotations">
    <h2>Mes annotations</h2>
    <form method="GET" action="">
        <label for="filter">Filtrer par statut :</label>
        <select name="filter" id="filter" onchange="this.form.submit()">
            <option value="all" {% if status_filter == "all" %}selected{% endif %}>Toutes</option>
            <option value="validated" {% if status_filter == "validated" %}selected{% endif %}>Validées</option>
            <option value="awaiting" {% if status_filter == "awaiting" %}selected{% endif %}>En attente</option>
            <option value="assigned" {% if status_filter == "assigned" %}selected{% endif %}>Attribuées</option>
        </select>
    </form>
    <br>
    <p><strong>{{ annotations_count }}</strong> annotation(s) trouvée(s).</p>
    
    <div class="database-container">
        {% if annotations %}
            {% for annotation in annotations %}

                <div class="annotation-card">
                    <div class="badge status-{{ annotation.sequence.sequence_status|lower|slugify }}">{{ annotation.sequence.get_sequence_status_display }}</div>
                    <h3> ID : {{ annotation.annotation_id }} </h3>
                    <strong>Séquence associée :</strong> {{ annotation.sequence.sequence_id }}</p>
                    <br> 
                    {{ annotation.annotation_text }}
                    <br>
                    <a href="{% url 'annoter' annotation.sequence.sequence_id %}" class="btn-view">Voir Détails/Modifier</a>
                </div>

            {% endfor %}
            
            <!-- pagination -->
            <div class="pagination">
                <span class="step-links">
                    {% if annotations.has_previous %}
                        <a href="?page=1&filter={{ status_filter }}">&laquo; Première</a>
                        <a href="?page={{ annotations.previous_page_number }}&filter={{ status_filter }}">Précédent</a>
                    {% endif %}

                    <span class="current">
                        Page {{ annotations.number }} sur {{ annotations.paginator.num_pages }}
                    </span>

                    {% if annotations.has_next %}
                        <a href="?page={{ annotations.next_page_number }}&filter={{ status_filter }}">Suivant</a>
                        <a href="?page={{ annotations.paginator.num_pages }}&filter={{ status_filter }}">Dernière &raquo;</a>
                    {% endif %}
                </span>
            </div>

        {% elif user.role == "lecteur" %}
            <p>En tant que lecteur vous n'avez pas accès à cette fonctionnalité.</p>
        {% endif %}

    </div>

</div>
<!-- Toast Notification -->
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="annotationToast" class="toast align-items-center text-bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body" id="toastMessage">
            </div>
            <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function () {
    var params = new URLSearchParams(window.location.search);
    var toastElement = document.getElementById("annotationToast");
    var toastMessage = document.getElementById("toastMessage");
    var toast = new bootstrap.Toast(toastElement);

    if (params.has("success")) {
        toastMessage.innerText = "L'annotation a été envoyée pour validation !";
        toast.show();
    } else if (params.has("saved")) {
        toastMessage.innerText = "L'annotation a été sauvegardée avec succès.";
        toast.show();
    }
});
</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
{% endblock %}

core/templates/core/profile_change_PSWD.html
{% extends "core/base_profile.html" %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Accueil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'profile' %}">Profil</a></li>
    <li class="breadcrumb-item active" aria-current="page">Changer mon mot de passe</li>
{% endblock %}

{% block profile_content %}
<div id="change_PSWD">
    <h3>Modifier mon mot de passe</h3>
    <form method="POST">
        {% csrf_token %}
        {{ password_form.as_p }}
        <button type="submit" class="btn">Changer le mot de passe</button>
    </form>
</div>
{% endblock %}

core/templates/core/test.html
<div class="database-results">
    {% for genome in genomes %}
        <div class="genome-card">
            <p>ID : {{ genome.genome_id }}</p>
            <p>Organisme : {{ genome.organism }}</p>
            <p>Type : {{ genome.get_genome_type_display }}</p>
            <p>Longueur de la séquence : {{ genome.genome_sequence|length }}</p>
        </div>
    {% empty %}
        <p>Aucun génome trouvé.</p>
    {% endfor %}
</div>

core/templates/core/visualisation.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Visualisation - EYAA{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Accueil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'genome_database' %}">Base de Données</a></li>

    {% if obj.sequence_id and obj.genome %}
        <li class="breadcrumb-item">
            <a href="{% url 'visualisation' 'genome' obj.genome.genome_id %}">Génome {{ obj.genome.genome_id }}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{ obj.sequence_id }}</li>

    {% elif obj.annotation_id and obj.sequence and obj.sequence.genome %}
        <li class="breadcrumb-item">
            <a href="{% url 'visualisation' 'genome' obj.sequence.genome.genome_id %}">Génome {{ obj.sequence.genome.genome_id }}</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'visualisation' 'sequence' obj.sequence.sequence_id %}">Séquence {{ obj.sequence.sequence_id }}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{ obj.annotation_id }}</li>

    {% endif %}

{% endblock %}


{% block content %}

<!-- lien ajouté dans style.css -->
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"> -->

<style>
    .status-red {
        color: white !important;
        background-color: red !important;
    }

    .status-orange {
        color: white !important;
        background-color: orange !important;
    }

    .status-yellow {
        color: black !important;
        background-color: yellow !important;
    }

    .status-green {
        color: white !important;
        background-color: green !important;
    }

    .btn-gray {
        background-color: #6c757d !important; 
        color: white !important;
    }
    .button-container {
    display: flex;
    justify-content: center;
    gap: 10px;
    margin: 20px 0;
    }
    .link-button {
        background-color: #007BFF;
        color: white;
        padding: 10px 20px;
        text-align: center;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
        text-decoration: none;
        display: inline-block;
        transition: background-color 0.3s;
    }
    .link-button:hover {
        background-color: #0056b3;
    }
    button {
    background-color: darkgray;
    color: white;
    padding: 10px 15px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: gray;
    }
</style>


<div class="container-fluid mt-4">

    {% if obj_type == "genome" %}

        <h1 class="text-center text-white">Génome : {{ obj.genome_id }}</h1>
        
        <div class="card mb-4">
            <div class="card-header">Détails du génome</div>
            <div class="card-body">
                <p><strong>ID du génome :</strong> {{ obj.genome_id }}</p>
                <p><strong>Organisme :</strong> {{ obj.organism }}</p>
                <p><strong>Type :</strong> {{ obj.get_genome_type_display }}</p>
                <p><strong>Génome annotée :</strong> {% if obj.is_annotated %}Oui{% else %}Non{% endif %}</p>
            </div>
        </div>

        
        <h2 class="text-white">CDS associées</h2>

        <form method="get" class="mb-4">
            <div class="input-group">
                <input type="text" name="search" class="form-control" value="{{ search_query }}" placeholder="Rechercher par nom du gène ou peptide">
                <button class="btn btn-secondary" type="submit">Rechercher</button>
            </div>
        </form>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nom du gène</th>
                    <th>Position</th>
                    <th>Statut</th>
                    <th>Séquence</th>
                    <th>Annotation</th>
                </tr>
            </thead>
            <tbody>
                {% for seq in page_obj %}
                <tr>
                    <td>{{ seq.sequence_id }}</td>
                    <td>
                        {% if seq.annotation and seq.get_sequence_status_display == "Validée" %}
                            {{ seq.gene_name }}
                        {% else %}
                            <span class="text-muted">Pas disponible</span>
                        {% endif %}
                    </td>
                    <td>{{ seq.sequence_start }} - {{ seq.sequence_stop }}</td>
                    <td class="{% if seq.get_sequence_status_display == 'Non-annotée' %}status-red{% elif seq.get_sequence_status_display == 'Attribuée' %}status-orange{% elif seq.get_sequence_status_display == 'En attente de validation' %}status-yellow{% elif seq.get_sequence_status_display == 'Validée' %}status-green{% endif %}">
                        {{ seq.get_sequence_status_display }}
                    </td>
                    <td>
                        <a href="{% url 'visualisation' obj_type='sequence' obj_id=seq.sequence_id %}" class="btn btn-secondary btn-sm">Informations de la séquence</a>
                    </td>
                    <td>
                        {% if seq.annotation and seq.get_sequence_status_display == "Validée" or seq.get_sequence_status_display == "En attente de validation" %}
                            <a href="{% url 'visualisation' obj_type='annotation' obj_id=seq.annotation.annotation_id %}" class="btn btn-gray btn-sm">Voir l'annotation</a>
                        {% else %}
                            <span class="text-muted">Aucune annotation disponible</span>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{ search_query }}">Précédente</a></li>
                {% endif %}
                <li class="page-item active"><span class="page-link">Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{ search_query }}">Suivante</a></li>
                {% endif %}
            </ul>
        </nav>

    {% elif obj_type == "sequence" %}

    <h1 class="text-center text-white">Séquence :  {{ obj.sequence_id }}</h1>

        <div class="card mb-4">
            <div class="card-header">Détails</div>
            <div class="card-body">
                <p><strong>ID de la séquence :</strong> {{ obj.sequence_id }}</p>
                <p><strong>Génome associé :</strong> {{ obj.genome.genome_id }}</p>
                <p><strong>Statut :</strong> {{ obj.get_sequence_status_display }}</p>
                <p><strong>Support :</strong> {{ obj.information_support }}</p>
                <p><strong>Brin :</strong> {{ obj.sequence_brin }}</p>
                <p><strong>Longueur :</strong> {{ obj.sequence_length }}</p>
                <p><strong>Nom du gène :</strong> {{ obj.gene_name }}</p>
                <p><strong>Nom du peptide :</strong> {{ obj.peptide_product }}</p>
            </div>
        </div>
        
        <h2 class="text-center text-white">Séquences</h2>

            <h3 class = "text-white">ADN :</h3>
            <textarea id="dna_sequence" readonly style="word-wrap: break-word; white-space: normal; background: #f4f4f4; padding: 10px; border-radius: 5px;width:100%; height: 150px; overflow-y: auto;">
                {{ obj.dna_sequence }}
            </textarea> <br>
            <button onclick="copyToClipboard('dna_sequence')">Copier ADN</button><br>
            <br>

            <h3 class = "text-white">Protéine :</h3>
            <textarea id="aa_sequence" readonly style="word-wrap: break-word; white-space: normal; background: #f4f4f4; padding: 10px; border-radius: 5px;width:100%; height: 150px; overflow-y: auto;">
                {{ obj.aa_sequence }}
            </textarea> <br>
            <button onclick="copyToClipboard('aa_sequence')">Copier Protéine</button> <br>
            <br>
        
        <a href="{% url 'visualisation' 'genome' obj.genome  %}" class="btn btn-secondary btn-sm">
            Voir le génome
        </a>
        
        {% if obj.annotation %}
            <a href="{% url 'visualisation' 'annotation' obj.annotation.annotation_id %}"  class="btn btn-secondary btn-sm">
                Voir l'annotation
            </a>
        {% endif %}

        <div class="button-container">
            <a href="https://blast.ncbi.nlm.nih.gov/Blast.cgi" class="link-button" target="_blank">Effectuer un blast</a>
            <a href="https://www.ebi.ac.uk/interpro/search/sequence/ " class="link-button" target="_blank">Recherche InterPro</a>
            <a href="https://www.uniprot.org/" class="link-button" target="_blank">Recherche sur UniProt</a>
        </div>

    {% elif obj_type == "annotation" %}
        <h1 class="text-center text-white">Annotation : {{ obj.annotation_id }}</h1>
        
    
        {% if obj.sequence.get_sequence_status_display != "Validée"%}
            <hr>
            <h2 style="color: darkorange;" >Attention cette annotation n'a pas encore été Validée</h2>
            <hr>
        {% endif%}

        <div class="card mb-4">
            <div class="card-header">Détails</div>
            <div class="card-body">
            <p><strong>ID de l'annotation :</strong> {{ obj.annotation_id }}</p>
            <p><strong>Auteur :</strong> {{ obj.annotation_author }}</p>
            <p><strong>Séquence associée :</strong> {{ obj.sequence.sequence_id }}</p>
            <p><strong>Nom du gène :</strong> {{ obj.sequence.gene_name }}</p>
            <p><strong>Nom du peptide :</strong> {{ obj.sequence.peptide_product }}</p>
            </div>
        </div>

        <h2 class="text-center text-white">Texte de l'annotation</h2>
            <pre style="word-wrap: break-word; white-space: normal; background: #f4f4f4; padding: 10px; border-radius: 5px; overflow-y: auto;">
                {{ obj.annotation_text }}
            </pre>
        

        <a href="{% url 'visualisation' 'genome' obj.sequence.genome  %}" class="btn btn-secondary btn-sm">
            Voir le génome
        </a>
        
            <a href="{% url 'visualisation' 'sequence' obj.sequence%}"  class="btn btn-secondary btn-sm">
                Voir la séquence
            </a>

            <div class="button-container">
                <a href="https://www.ebi.ac.uk/interpro/search/text/" class="link-button" target="_blank">Recherche InterPro</a>
                <a href="https://www.uniprot.org/" class="link-button" target="_blank">Recherche sur UniProt</a>
            </div>

       
    {% else %}
        <p>Type d'objet non reconnu.</p>
    {% endif %}

    <footer>
        <a href="{% url 'genome_database' %}" style="color:white">Retour à la base de données</a>
    </footer>

    <script>
        function copyToClipboard(id) {
            var copyText = document.getElementById(id);

            // Selectionner le texte du textarea
            copyText.select();
            copyText.setSelectionRange(0, 99999); // Pour les appareils mobiles

            // Copier dans le presse-papiers
            navigator.clipboard.writeText(copyText.value).then(function() {
            alert('Séquence copiée dans le presse-papiers');
            }).catch(function(error) {
            console.error('Erreur lors de la copie dans le presse-papiers: ', error);
            });
        }
    </script>

{% endblock %}